@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LEFT_RIGHT()

Container(loadbalancer, "Load Balancer", "LB", "Distribui processamento para os nós")

Container_Boundary(filters, "Filtros"){
    Component(img_loader, "Image Loader", "Filtro", "Recupera dados crus da imagem")

    Component(filter_a, "Filtro de pre-processamento", "Filtro", "Decodifica, normaliza e redimensiona a imagem")

    Component(filter_b, "Filtro de transformação", "Filtro", "Aplica transformações")

    Component(filter_c, "Filtro de IA", "Filtro", "Executa inferência de aprendizado de máquina para aprimoramento")

    Component(img_exporter, "Exportador", "Filtro", "Gera a imagem processada para armazenamento")
}

Rel(loadbalancer, filters, "Entrega dados e gerencia")

Rel(img_loader, filter_a, "Pipe dados de imagem", "pipe de processamento")
Rel(filter_a, filter_b, "Pipe de transformação", "pipe de processamento")
Rel(filter_b, filter_c, "Pipe de melhoria da imagem", "pipe de processamento")
Rel(filter_c, img_exporter, "Pipe de imagem final", "pipe de processamento")

@enduml
